### ISSUE TITLE
Despliegue aplicación

### ISSUE THREAD

**Issue by UO271548** [Arquisoft/dede_es1a#236]
Se debe modificar el despliegue de la aplicación para que se conecte por https y permita la conexión con los PODs por parte de los usuarios

**Comment by UO271548** [comment]
Hemos desplegado la aplicación en heroku para solucionar los problemas que teníamos con AWS

link: https://dede-es1a-webapp.herokuapp.com/

**Comment by pglez82** [comment]
Lo he probado y me ha funcionado correctamente. Enhorabuena por el trabajo.

**Comment by cidinene** [comment]
Lo he probado y también me funciona. Buen trabajo

**Comment by labra** [comment]
Idem...lo he probado y también me funcionó.

**Comment by HugoLebredo** [comment]
Probado y funcionándo.

**Comment by UO271548** [comment]
Gracias! ¿Cerramos entonces ya el issue?

**Comment by labra** [comment]
Sí, podéis cerrarlo.
