### ISSUE TITLE
Decidir de qué hacer la tienda

### ISSUE THREAD

**Issue by UO276853** [Arquisoft/dede_es1a#29]
Que productos se van a vender?

**Comment by valydumitru01** [comment]
### Proposición: Tienda de rocas o piedras.
Podemos clasificarlas por minerales, formas, colores, localización, dureza, etc. 🪨 ⛰️ 
![imagen](https://user-images.githubusercontent.com/62762857/155162254-80b59d87-8f2a-46b6-a7ff-5cd364c9732a.png)


Sería original.

Podemos incluir la roca mascota, es graciosa 😆 

https://www.amazon.com/Pet-Rock-Authentic-Approved-Original/dp/B07KN9FK4B
![imagen](https://user-images.githubusercontent.com/62762857/155162150-fa780e83-1e51-4ba6-a200-a717f8947376.png)
