### ISSUE TITLE
Modificar participantes del readme

### ISSUE THREAD

**Issue by UO276853** [Arquisoft/dede_es1a#67]
El participante Mario no va a poder continuar con el proyecto, habrá que modificar la lista de desarrolladores que está en los readme de la rama develop.

**Comment by valydumitru01** [comment]
Puedes hacerlo tu Jorge?

**Comment by UO271548** [comment]
Ya se ha corregido este issue en el commit https://github.com/Arquisoft/dede_es1a/commit/ebdf598ebd310bce40570a524192b794bba90586
